routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Основные пользовательские страницы
|--------------------------------------------------------------------------
*/

Route::middleware(['web'])->group(function () {
    /** Домашняя страница */
    Route::view('/', 'app')->name('home');

    /** Страницы методик */
    Route::view('/method/{path?}', 'app')->where('path', '.*');
    Route::view('/methods', 'app');

    /** Всероссийская научно-техническая конференция */
    Route::view('conf/{path?}', 'app')->where('path', '.*');
});

Route::middleware(['auth'])->group(function () {
    /** Страницы прохождения тестирования */
    Route::view('test/{id}', 'app');
    Route::view('tests', 'app')->name('test.main');

    /** Страница настроек профиля */
    Route::view('/profile/{path?}', 'app')->where('path', '.*')->name('profile.main');
});

/*
|--------------------------------------------------------------------------
| Документы из локального диска и базы данных
|--------------------------------------------------------------------------
*/

Route::get('/document', 'Database\mddb\DocumentController@load');

Route::get('/document/local/{path}', 'Database\mddb\DocumentController@localLoad')
    ->where('path', '.*');

Route::get('/document/conf', 'Database\conf\DocumentController@load');

/*
|--------------------------------------------------------------------------
| Логирование ошибок и временные ссылки
|--------------------------------------------------------------------------
*/

Route::view('/logs', 'develop.logs')->middleware(['auth']);

Route::redirect('/api-doc', 'https://cmkd-rest-api.postman.co/collection/13826413-95a2481c-f7a1-4aca-857d-cfeec8baba91?source=rip_html');

/** Информационная страница об Углеве В.А. */
Route::view('uglev-about', 'other.uglev-about');

/*
|--------------------------------------------------------------------------
| Аутентификация, авторизация и регистрация
|--------------------------------------------------------------------------
*/

Route::get('/auth', 'Database\mddb\AuthController@auth');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');
Route::get('/register/{login}/exists', 'Auth\RegisterController@userLoginExists');

/*
|--------------------------------------------------------------------------
| Отладка и пробы
|--------------------------------------------------------------------------
*/

Route::middleware('debug')->group(function () {
    Route::get('/purpose-grid-only', 'Other\DevelopController@grid');
    Route::any('/purpose-test-only', 'Other\DevelopController@test');
});

Route::get('/cache/flm-builder', 'Other\CacheController@flmBuilderStat');

/*
|--------------------------------------------------------------------------
| Консольные пути по выдачи Blade компонентов [ ПЕРЕПИСАТЬ ]
|--------------------------------------------------------------------------
*/

/**
 * Консоль
 */
Route::name('console.')->prefix('console')->middleware(['auth', 'permission:admin|console'])->group(function () {
    Route::get('', 'ConsoleController@main')->name('main');

    Route::name('spec.')->group(function () {
        Route::get('specialities', 'ConsoleController@Speciality')->name('main');
    });

    Route::name('branch.')->group(function () {
        Route::get('branches', 'ConsoleController@Branch')->name('main');
        Route::post('branches', 'ConsoleController@BranchNext')->name('next');
        Route::post('branches/search', 'ConsoleController@BranchSearch')->name('search');
    });

    Route::name('subgroup.')->group(function () {
        Route::get('subgroups', 'ConsoleController@Subgroup')->name('main');
        Route::post('subgroups', 'ConsoleController@SubgroupNext')->name('next');
        Route::post('subgroups/search', 'ConsoleController@SubgroupSearch')->name('search');
    });

    Route::name('disc.')->group(function () {
        Route::get('disciplines', 'ConsoleController@Discipline')->name('main');
        Route::post('disciplines', 'ConsoleController@DisciplineNext')->name('next');
        Route::post('disciplines/search', 'ConsoleController@DisciplineSearch')->name('search');
    });

    Route::name('competence.')->group(function () {
        Route::get('competences', 'ConsoleController@Competence')->name('main');
        Route::post('competence', 'ConsoleController@CompetenceNext')->name('next');
    });

    Route::name('test.')->group(function () {
        Route::get('tests', 'ConsoleController@Test')->name('main');
        Route::post('tests', 'ConsoleController@TestNext')->name('next');
        Route::post('tests/search', 'ConsoleController@TestSearch')->name('search');
    });

    Route::name('quest.')->group(function () {
        Route::get('quests', 'ConsoleController@Quest')->name('main');
        Route::post('quests', 'ConsoleController@QuestNext')->name('next');
        Route::post('quests/search', 'ConsoleController@QuestSearch')->name('search');
    });

    Route::name('user.')->group(function () {
        Route::get('users', 'ConsoleController@User')->name('main');
        Route::post('users', 'ConsoleController@UserNext')->name('next');
        Route::post('users/search', 'ConsoleController@UserSearch')->name('search');
    });

    Route::name('passed.')->group(function () {
        Route::get('passed', 'ConsoleController@Passed')->name('main');
        Route::post('passed', 'ConsoleController@PassedNext')->name('next');
        Route::post('passed/search', 'ConsoleController@PassedSearch')->name('search');
        Route::get('passed/download/{id}', 'ConsoleController@PassedDownload')->name('download');
    });

    Route::name('conference.')->group(function () {
        Route::get('conference', 'ConsoleController@Conference')->name('main');
    });

    Route::name('develop.')->middleware(['permission:develop'])->group(function () {
        Route::get('develop', 'ConsoleController@Develop')->name('main');
    });
});

/**
 * Редактор
 */
Route::prefix('editor')->middleware(['auth', 'permission:admin|console'])->group(function () {
    /** Редактирование статьи */
    Route::get('/article/{id}', 'EditorController@Article');

    /** Редактирование участника */
    Route::get('/member/{id}', 'EditorController@Member');
});

Route::name('editor.')->prefix('console')->middleware(['auth', 'permission:admin|console|editor'])->group(function () {
    Route::name('spec.')->prefix('speciality')->group(function () {
        Route::get('new', 'EditorController@SpecialityNew')->name('new');
        Route::post('create', 'EditorController@SpecialityCreate')->name('create');
        Route::get('{id}', 'EditorController@SpecialityEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SpecialityUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SpecialityDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SpecialityPairs')->name('pairs');
    });

    Route::name('branch.')->prefix('branch')->group(function () {
        Route::get('new', 'EditorController@BranchNew')->name('new');
        Route::post('create', 'EditorController@BranchCreate')->name('create');
        Route::get('{id}', 'EditorController@BranchEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@BranchUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@BranchDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@BranchPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@BranchUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@BranchUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@BranchUserPairs')->name('userpairs');
    });

    Route::name('subgroup.')->prefix('subgroup')->group(function () {
        Route::get('new', 'EditorController@SubgroupNew')->name('new');
        Route::post('create', 'EditorController@SubgroupCreate')->name('create');
        Route::get('{id}', 'EditorController@SubgroupEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SubgroupUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SubgroupDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SubgroupPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@SubgroupUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@SubgroupUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@SubgroupUserPairs')->name('userpairs');
        Route::post('testupdate/{id}', 'EditorController@SubgroupTestUpdate')->name('testupdate');
        Route::post('testsearch/', 'EditorController@SubgroupTestSearch')->name('testsearch');
        Route::post('testpairs/{id}', 'EditorController@SubgroupTestPairs')->name('testpairs');
    });

    Route::name('disc.')->prefix('discipline')->group(function () {
        Route::get('new', 'EditorController@DisciplineNew')->name('new');
        Route::post('create', 'EditorController@DisciplineCreate')->name('create');
        Route::get('{id}', 'EditorController@DisciplineEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@DisciplineUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@DisciplineDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@DisciplinePairs')->name('pairs');
        Route::post('branchupdate/{id}', 'EditorController@DisciplineBranchUpdate')->name('branchupdate');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Sanctum\NewAccessToken;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasRoles, Notifiable;

    public $timestamps = true;

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $table = 'user';

    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'last_visit' => 'datetime',
    ];

    protected $fillable = [
        'surname',
        'name',
        'patronym',
        'login',
        'email',
        'password',
        'last_visit',
    ];

    protected $hidden = [
        'password',
        'status_id',
        'branch_id',
        'remember_token',
    ];

    /**
     * Связь Многие к Одному с Branch
     */
    public function branch()
    {
        return $this->belongsTo(\App\Models\mddb\Branch::class, 'branch_id');
    }

    /**
     * Связь Многие к Многие с Subgroup
     */
    public function subgroups()
    {
        return $this->belongsToMany(\App\Models\mddb\Subgroup::class, 'userlinksubgroup', 'user_id', 'subgroup_id');
    }

    /**
     * Связь Один к Многие с Basket
     */
    public function baskets()
    {
        return $this->hasMany(\App\Models\mddb\Basket::class, 'user_id');
    }

    /**
     * Связь Один к Многие с Test
     */
    public function tests()
    {
        return $this->hasMany(\App\Models\mddb\Test::class, 'owner');
    }

    /**
     * Связь Один к Многие с Discipline
     */
    public function disciplines()
    {
        return $this->hasMany(\App\Models\mddb\Discipline::class, 'owner');
    }

    /**
     * Связь Многие к Одному с Userstatus
     */
    public function userstatus()
    {
        return $this->belongsTo(\App\Models\mddb\Userstatus::class, 'status_id');
    }

    /**
     * Связь Один к Многие с UserToken
     */
    public function tokens()
    {
        return $this->hasMany(UserToken::class, 'user_id');
    }

    /**
     * Полное имя пользователя
     */
    public function name()
    {
        return $this->surname.' '.$this->name.' '.$this->patronym;
    }

    /**
     * Создать новый персональный токен доступа для пользователя
     */
    public function createToken(string $name, array $abilities = ['*'])
    {
        $token = $this->tokens()->create([
            'name' => $name,
            'token' => hash('sha256', $plainTextToken = Str::random(40)),
            'abilities' => $abilities,
        ]);

        return new NewAccessToken($token, $token->getKey().'|'.$plainTextToken);
    }
}

app/Http/Controllers/Database/mddb/UserController.php
<?php

namespace App\Http\Controllers\Database\mddb;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\User;
use App\Models\mddb\Userstatus;

class UserController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Пользователь
    |--------------------------------------------------------------------------
    */

    public function __construct()
    {
        // $this->middleware('')->only([ '' ]);
    }

    /**
     * Получение информации о пользователе
     *
     * GET /api/user/{id}
     */
    public function user($id)
    {
        $user = User::find($id);

        if (!$user)
            return $this->toJson(null);

        $user->load(['userstatus']);

        if ($user->branch) {
            $user->branch->setHidden(['speciality_id'])->speciality;
        }

        return $this->toJson($user);
    }

    /**
     * Получение списка пройденных тестов пользователем
     *
     * GET /api/user/{id}/basket
     */
    public function basket($id)
    {
        $user = User::find($id);

        if (!$user)
            return $this->toJson(['message' => 'Пользователь не найден'], 422);

        $baskets = $user->baskets()->with(['test'])->get();

        $baskets->each(function ($elem) {
            $elem->setHidden([
                'user_id',
                'test_id',
            ]);
        });

        return $this->toJson($baskets);
    }

    /**
     * Получение списка пользователей
     *
     * POST /api/users
     */
    public function users(Request $request)
    {
        $users = User::query();

        if ($request->filled('login'))
            $users->where('login', 'like', str_replace("*", "%", $request->login));
        if ($request->filled('surname'))
            $users->where('surname', 'like', str_replace("*", "%", $request->surname));
        if ($request->filled('name'))
            $users->where('name', 'like', str_replace("*", "%", $request->name));
        if ($request->filled('patronym'))
            $users->where('patronym', 'like', str_replace("*", "%", $request->patronym));

        $users = $users->get();
        $total = $users->count();

        $users = $this->modelsPaginator($users, $request->perPage, $request->pageCount);

        return $this->toJson([
            'users' => $users,
            'total' => $total,
        ]);
    }

    /**
     * Получение упрощённого списка пользователей
     *
     * POST /api/users/short
     */
    public function shortusers(Request $request)
    {
        $users = User::query();

        $users = $users
            ->orderBy('surname')
            ->get();

        $users = $users->makeHidden(['email', 'login', 'created_at', 'updated_at', 'last_visit']);

        return $this->toJson($users);
    }

    /**
     * Получение списка занимаемых должностейPOST
     *
     * GET /api/userstatus
     */
    public function userStatus()
    {
        $statuses = Userstatus::orderBy('order')->get();

        return $this->toJson($statuses);
    }
}

resources/views/editor/user/edit.blade.php
@extends('layouts.main', ['title' => config('app.name').' - Пользователь - '.$user->name()])

@section('content')

<div class="ui one column stackable grid">

    <div class="sixteen wide tablet twelve wide computer centered column">

        <div class="ui tiny breadcrumb">
            <a class="section bread" href="{{ route('console.main') }}">Консоль</a>
            <i class="right angle icon divider"></i>
            <a class="section bread" href="{{ route('console.user.main') }}">Пользователи</a>
            <i class="right angle icon divider"></i>
            <div class="section active">#{{ $user->id }}</div>
        </div>

        <div class="ui divider"></div>

        <div class="ui fluid accordion">
            <div class="title active">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Основные параметры</b>
            </div>

            <div class="content active">

                @include('editor.user.parts.edit')

            </div>
        </div>

        <div class="ui divider"></div>

        <div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Пройденные тесты</b>
            </div>

            <div class="content">

                @include('editor.user.parts.passed')

            </div>
        </div>

        @can('admin')
            <div class="ui divider"></div>

            <div class="ui fluid accordion">
                <div class="title">
                    <i class="dropdown icon"></i>
                    <b style="font-size:1.25rem;">Настройка прав</b>
                </div>

                <div class="content">

                    @include('editor.user.parts.permission')

                </div>
            </div>
        @endcan

    </div>
</div>


@endsection

@section('script')

<script type="text/javascript">
    @can('admin')
        {{-- КНОПКА УДАЛИТЬ [button_delete] --}}
        const bd = function(){
            let val = confirm("Удаление пользователя постоянно и приведет к очистке всех данных, связанных с ним. Вы уверены, что хотите удалить пользователя?");

            if (val) $("#delete-form").attr("action", "{{ route('editor.user.delete', [$user->id]) }}").submit();
        };
        {{-- СБРОСИТЬ ПАРОЛЬ [reset_password] --}}
        const rp = function(){
            $("#btn-reset").addClass("loading");

            $.ajax({
                method: "POST",
                url: "{{ route('editor.user.reset', [$user->id]) }}",
                headers: {
                    "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr('content'),
                },
                dataType: "json",
                complete: function(){
                    $("#btn-reset").removeClass("loading");
                },
                success: function(){
                    $("#btn-reset").addClass("positive icon").off("click").html('<i class="check icon"></i>');
                },
                error: function(jq, text, err){
                    $('#message').children(".ui.header").text(jq.responseJSON.header);
                    $('#message').children("p").text(jq.responseJSON.message);
                    $('#message').closest(".grid").slideDown(50);
                },
            });
        };

        {{-- ОБНОВИТЬ ПРАВА [update_permissions] --}}
        const up = function(ev){
            ev.preventDefault();

            $("#btn-permission").addClass("loading");

            $.ajax({
                method: "POST",
                url: "{{ route('editor.user.permission', $user->id) }}",
                headers: {
                    "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr('content'),
                },
                dataType: "json",
                data: $(this).serialize(),
                complete: function(){
                    $("#btn-permission").removeClass("loading");
                },
                success: function(){
                    $("#btn-permission").addClass("positive icon").off("click").html('<i class="check icon"></i>');
                },
                error: function(jq, text, err){
                    $('#message').children(".ui.header").text(jq.responseJSON.header);
                    $('#message').children("p").text(jq.responseJSON.message);
                    $('#message').closest(".grid").slideDown(50);
                },
            });
        };

        $("#delete-item").click(bd);
        $("#fm-permission").submit(up);
        $("#permissions").dropdown("set selected", {!! $has !!});
        $("#btn-reset").click(function(){ if (confirm("Вы уверены, что хотите сбросить пароль данного пользователя?")) rp() });
    @endcan

</script>

@endsection