routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Основные пользовательские страницы
|--------------------------------------------------------------------------
*/

Route::middleware(['web'])->group(function () {
    /** Домашняя страница */
    Route::view('/', 'app')->name('home');

    /** Страницы методик */
    Route::view('/method/{path?}', 'app')->where('path', '.*');
    Route::view('/methods', 'app');

    /** Всероссийская научно-техническая конференция */
    Route::view('conf/{path?}', 'app')->where('path', '.*');
});

Route::middleware(['auth'])->group(function () {
    /** Страницы прохождения тестирования */
    Route::view('test/{id}', 'app');
    Route::view('tests', 'app')->name('test.main');

    /** Страница настроек профиля */
    Route::view('/profile/{path?}', 'app')->where('path', '.*')->name('profile.main');
});

/*
|--------------------------------------------------------------------------
| Документы из локального диска и базы данных
|--------------------------------------------------------------------------
*/

Route::get('/document', 'Database\mddb\DocumentController@load');

Route::get('/document/local/{path}', 'Database\mddb\DocumentController@localLoad')
    ->where('path', '.*');

Route::get('/document/conf', 'Database\conf\DocumentController@load');

/*
|--------------------------------------------------------------------------
| Логирование ошибок и временные ссылки
|--------------------------------------------------------------------------
*/

Route::view('/logs', 'develop.logs')->middleware(['auth']);

Route::redirect('/api-doc', 'https://cmkd-rest-api.postman.co/collection/13826413-95a2481c-f7a1-4aca-857d-cfeec8baba91?source=rip_html');

/** Информационная страница об Углеве В.А. */
Route::view('uglev-about', 'other.uglev-about');

/*
|--------------------------------------------------------------------------
| Аутентификация, авторизация и регистрация
|--------------------------------------------------------------------------
*/

Route::get('/auth', 'Database\mddb\AuthController@auth');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');
Route::get('/register/{login}/exists', 'Auth\RegisterController@userLoginExists');

/*
|--------------------------------------------------------------------------
| Отладка и пробы
|--------------------------------------------------------------------------
*/

Route::middleware('debug')->group(function () {
    Route::get('/purpose-grid-only', 'Other\DevelopController@grid');
    Route::any('/purpose-test-only', 'Other\DevelopController@test');
});

Route::get('/cache/flm-builder', 'Other\CacheController@flmBuilderStat');

/*
|--------------------------------------------------------------------------
| Консольные пути по выдачи Blade компонентов [ ПЕРЕПИСАТЬ ]
|--------------------------------------------------------------------------
*/

/**
 * Консоль
 */
Route::name('console.')->prefix('console')->middleware(['auth', 'permission:admin|console'])->group(function () {
    Route::get('', 'ConsoleController@main')->name('main');

    Route::name('spec.')->group(function () {
        Route::get('specialities', 'ConsoleController@Speciality')->name('main');
    });

    Route::name('branch.')->group(function () {
        Route::get('branches', 'ConsoleController@Branch')->name('main');
        Route::post('branches', 'ConsoleController@BranchNext')->name('next');
        Route::post('branches/search', 'ConsoleController@BranchSearch')->name('search');
    });

    Route::name('subgroup.')->group(function () {
        Route::get('subgroups', 'ConsoleController@Subgroup')->name('main');
        Route::post('subgroups', 'ConsoleController@SubgroupNext')->name('next');
        Route::post('subgroups/search', 'ConsoleController@SubgroupSearch')->name('search');
    });

    Route::name('disc.')->group(function () {
        Route::get('disciplines', 'ConsoleController@Discipline')->name('main');
        Route::post('disciplines', 'ConsoleController@DisciplineNext')->name('next');
        Route::post('disciplines/search', 'ConsoleController@DisciplineSearch')->name('search');
    });

    Route::name('competence.')->group(function () {
        Route::get('competences', 'ConsoleController@Competence')->name('main');
        Route::post('competence', 'ConsoleController@CompetenceNext')->name('next');
    });

    Route::name('test.')->group(function () {
        Route::get('tests', 'ConsoleController@Test')->name('main');
        Route::post('tests', 'ConsoleController@TestNext')->name('next');
        Route::post('tests/search', 'ConsoleController@TestSearch')->name('search');
    });

    Route::name('quest.')->group(function () {
        Route::get('quests', 'ConsoleController@Quest')->name('main');
        Route::post('quests', 'ConsoleController@QuestNext')->name('next');
        Route::post('quests/search', 'ConsoleController@QuestSearch')->name('search');
    });

    Route::name('user.')->group(function () {
        Route::get('users', 'ConsoleController@User')->name('main');
        Route::post('users', 'ConsoleController@UserNext')->name('next');
        Route::post('users/search', 'ConsoleController@UserSearch')->name('search');
    });

    Route::name('passed.')->group(function () {
        Route::get('passed', 'ConsoleController@Passed')->name('main');
        Route::post('passed', 'ConsoleController@PassedNext')->name('next');
        Route::post('passed/search', 'ConsoleController@PassedSearch')->name('search');
        Route::get('passed/download/{id}', 'ConsoleController@PassedDownload')->name('download');
    });

    Route::name('conference.')->group(function () {
        Route::get('conference', 'ConsoleController@Conference')->name('main');
    });

    Route::name('develop.')->middleware(['permission:develop'])->group(function () {
        Route::get('develop', 'ConsoleController@Develop')->name('main');
    });
});

/**
 * Редактор
 */
Route::prefix('editor')->middleware(['auth', 'permission:admin|console'])->group(function () {
    /** Редактирование статьи */
    Route::get('/article/{id}', 'EditorController@Article');

    /** Редактирование участника */
    Route::get('/member/{id}', 'EditorController@Member');
});

Route::name('editor.')->prefix('console')->middleware(['auth', 'permission:admin|console|editor'])->group(function () {
    Route::name('spec.')->prefix('speciality')->group(function () {
        Route::get('new', 'EditorController@SpecialityNew')->name('new');
        Route::post('create', 'EditorController@SpecialityCreate')->name('create');
        Route::get('{id}', 'EditorController@SpecialityEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SpecialityUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SpecialityDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SpecialityPairs')->name('pairs');
    });

    Route::name('branch.')->prefix('branch')->group(function () {
        Route::get('new', 'EditorController@BranchNew')->name('new');
        Route::post('create', 'EditorController@BranchCreate')->name('create');
        Route::get('{id}', 'EditorController@BranchEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@BranchUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@BranchDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@BranchPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@BranchUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@BranchUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@BranchUserPairs')->name('userpairs');
    });

    Route::name('subgroup.')->prefix('subgroup')->group(function () {
        Route::get('new', 'EditorController@SubgroupNew')->name('new');
        Route::post('create', 'EditorController@SubgroupCreate')->name('create');
        Route::get('{id}', 'EditorController@SubgroupEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SubgroupUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SubgroupDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SubgroupPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@SubgroupUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@SubgroupUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@SubgroupUserPairs')->name('userpairs');
        Route::post('testupdate/{id}', 'EditorController@SubgroupTestUpdate')->name('testupdate');
        Route::post('testsearch/', 'EditorController@SubgroupTestSearch')->name('testsearch');
        Route::post('testpairs/{id}', 'EditorController@SubgroupTestPairs')->name('testpairs');
    });

    Route::name('disc.')->prefix('discipline')->group(function () {
        Route::get('new', 'EditorController@DisciplineNew')->name('new');
        Route::post('create', 'EditorController@DisciplineCreate')->name('create');
        Route::get('{id}', 'EditorController@DisciplineEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@DisciplineUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@DisciplineDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@DisciplinePairs')->name('pairs');
        Route::post('branchupdate/{id}', 'EditorController@DisciplineBranchUpdate')->name('branchupdate');

app/Models/mddb/Subgroup.php
<?php

namespace App\Models\mddb;

use Illuminate\Database\Eloquent\Model;

class Subgroup extends Model
{
    protected $table = 'subgroup'; 
    public $timestamps = false;

    protected $fillable = [
        'name',
        'portrait',
        'owner',
    ];

    protected $hidden = [

    ];

    /**
     * Связь Многие к Многие с User
     */
    public function users()
    {
        return $this->belongsToMany(\App\Models\User::class, 'userlinksubgroup', 'subgroup_id', 'user_id');
    }

    /**
     * Связь Многие к Многие с Test
     */
    public function tests()
    {
        return $this->belongsToMany(Test::class, 'subgrouplinktest', 'subgroup_id', 'test_id');
    }

    /**
     * Связь Многие к Одному с User
     */
    public function userowner()
    {
        return $this->belongsTo(\App\Models\User::class, 'owner');
    }
}

app/Http/Controllers/Database/mddb/SubgroupController.php
<?php

namespace App\Http\Controllers\Database\mddb;

use App\Models;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SubgroupController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Подгруппы
    |--------------------------------------------------------------------------
    */

    public function __construct()
    {
        // $this->middleware('')->only([ '' ]);
    }
}

resources/views/console/subgroup/subgroups.blade.php
@extends('layouts.main', ['title' => config('app.name').' - Спецгруппы'])

@section('content')

<!-- [DELETE] -->

<div class="ui stackable grid">
    @include('console.parts.menu')
    
    <div class="column" style="flex-grow:1;">
        
        <div class="ui one column grid">
            <div class="column" style="padding-bottom:0 !important;">
                
                {{-- КНОПКА СОЗДАТЬ --}}
                @canany(['admin', 'editor'])
					<div class="ui grid">
						<div class="one column right aligned row">
							<div class="column">
								<a class="ui positive tiny button" href="{{ route('editor.subgroup.new') }}">Создать</a>
							</div>
						</div>
					</div>
                @endcanany
                
                {{-- ФОРМА ПОИСКА --}}
                <div class="ui form">
                    
                    {{-- СОРТИРОВКА --}}
                    <div class="field">
                        <div class="ui dropdown" tabindex="-1">
                            <i class="sort amount down icon"></i>
                            <span>Сортировать</span>
                            <div class="menu transition hidden" tabindex="-1">
                                <a class="item{{ Request::input('sort') == null ? ' active selected' : '' }}" href="{{ route('console.subgroup.main') }}">По алфавиту (А - Я)</a>
                                <a class="item{{ Request::input('sort') == 'za' ? ' active selected' : '' }}" href="{{ route('console.subgroup.main', ['sort' => 'za']) }}">По алфавиту (Я - А)</a>
                            </div>
                        </div>
                    </div>
                    
                    {{-- ПОИСКОВА СТРОКА --}}
                    <div class="field">
                        <div class="column">
                            <div class="ui fluid icon input">
                                <input id="search-text" type="text" placeholder="Спецгруппы">
                                <i id="search-icon" class="search link icon"></i>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        
        <div class="ui one column grid">
            <div id="models" class="column" route-next="{{ route('console.subgroup.next', ['sort' => Request::input('sort')]) }}" route-search="{{ route('console.subgroup.search', ['sort' => Request::input('sort')]) }}">
                <table class="ui very basic unstackable table">
                   	<thead>
                   		<tr>
                   			<th class="eight wide">Наименование</th>
                   			<th class="seven wide">Участников</th>
                   			<th class="one wide"></th>
                   		</tr>
                   	</thead>
                    <tbody id="models-list" page-count="1"></tbody>
                </table>
            </div>
            <div class="row centered">
                <button id="models-next" class="ui button basic small" type="button">Загрузить еще</button>
            </div>
        </div>
        
    </div>
</div>

@endsection

@section('script')

@include('console.parts.search')

@endsection