routes/web.php
    Route::view('/profile/{path?}', 'app')->where('path', '.*')->name('profile.main');
});

/*
|--------------------------------------------------------------------------
| Документы из локального диска и базы данных
|--------------------------------------------------------------------------
*/

Route::get('/document', 'Database\mddb\DocumentController@load');

Route::get('/document/local/{path}', 'Database\mddb\DocumentController@localLoad')
    ->where('path', '.*');

Route::get('/document/conf', 'Database\conf\DocumentController@load');

/*
|--------------------------------------------------------------------------
| Логирование ошибок и временные ссылки
|--------------------------------------------------------------------------
*/

Route::view('/logs', 'develop.logs')->middleware(['auth']);

Route::redirect('/api-doc', 'https://cmkd-rest-api.postman.co/collection/13826413-95a2481c-f7a1-4aca-857d-cfeec8baba91?source=rip_html');

/** Информационная страница об Углеве В.А. */
Route::view('uglev-about', 'other.uglev-about');

/*
|--------------------------------------------------------------------------
| Аутентификация, авторизация и регистрация
|--------------------------------------------------------------------------
*/

Route::get('/auth', 'Database\mddb\AuthController@auth');

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::post('/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/register', 'Auth\RegisterController@register');
Route::get('/register/{login}/exists', 'Auth\RegisterController@userLoginExists');

/*
|--------------------------------------------------------------------------
| Отладка и пробы
|--------------------------------------------------------------------------
*/

Route::middleware('debug')->group(function () {
    Route::get('/purpose-grid-only', 'Other\DevelopController@grid');
    Route::any('/purpose-test-only', 'Other\DevelopController@test');
});

Route::get('/cache/flm-builder', 'Other\CacheController@flmBuilderStat');

/*
|--------------------------------------------------------------------------
| Консольные пути по выдачи Blade компонентов [ ПЕРЕПИСАТЬ ]
|--------------------------------------------------------------------------
*/

/**
 * Консоль
 */
Route::name('console.')->prefix('console')->middleware(['auth', 'permission:admin|console'])->group(function () {
    Route::get('', 'ConsoleController@main')->name('main');

    Route::name('spec.')->group(function () {
        Route::get('specialities', 'ConsoleController@Speciality')->name('main');
    });

    Route::name('branch.')->group(function () {
        Route::get('branches', 'ConsoleController@Branch')->name('main');
        Route::post('branches', 'ConsoleController@BranchNext')->name('next');
        Route::post('branches/search', 'ConsoleController@BranchSearch')->name('search');
    });

    Route::name('subgroup.')->group(function () {
        Route::get('subgroups', 'ConsoleController@Subgroup')->name('main');
        Route::post('subgroups', 'ConsoleController@SubgroupNext')->name('next');
        Route::post('subgroups/search', 'ConsoleController@SubgroupSearch')->name('search');
    });

    Route::name('disc.')->group(function () {
        Route::get('disciplines', 'ConsoleController@Discipline')->name('main');
        Route::post('disciplines', 'ConsoleController@DisciplineNext')->name('next');
        Route::post('disciplines/search', 'ConsoleController@DisciplineSearch')->name('search');
    });

    Route::name('competence.')->group(function () {
        Route::get('competences', 'ConsoleController@Competence')->name('main');
        Route::post('competence', 'ConsoleController@CompetenceNext')->name('next');
    });

    Route::name('test.')->group(function () {
        Route::get('tests', 'ConsoleController@Test')->name('main');
        Route::post('tests', 'ConsoleController@TestNext')->name('next');
        Route::post('tests/search', 'ConsoleController@TestSearch')->name('search');
    });

    Route::name('quest.')->group(function () {
        Route::get('quests', 'ConsoleController@Quest')->name('main');
        Route::post('quests', 'ConsoleController@QuestNext')->name('next');
        Route::post('quests/search', 'ConsoleController@QuestSearch')->name('search');
    });

    Route::name('user.')->group(function () {
        Route::get('users', 'ConsoleController@User')->name('main');
        Route::post('users', 'ConsoleController@UserNext')->name('next');
        Route::post('users/search', 'ConsoleController@UserSearch')->name('search');
    });

    Route::name('passed.')->group(function () {
        Route::get('passed', 'ConsoleController@Passed')->name('main');
        Route::post('passed', 'ConsoleController@PassedNext')->name('next');
        Route::post('passed/search', 'ConsoleController@PassedSearch')->name('search');
        Route::get('passed/download/{id}', 'ConsoleController@PassedDownload')->name('download');
    });

    Route::name('conference.')->group(function () {
        Route::get('conference', 'ConsoleController@Conference')->name('main');
    });

    Route::name('develop.')->middleware(['permission:develop'])->group(function () {
        Route::get('develop', 'ConsoleController@Develop')->name('main');
    });
});

/**
 * Редактор
 */
Route::prefix('editor')->middleware(['auth', 'permission:admin|console'])->group(function () {
    /** Редактирование статьи */
    Route::get('/article/{id}', 'EditorController@Article');

    /** Редактирование участника */
    Route::get('/member/{id}', 'EditorController@Member');
});

Route::name('editor.')->prefix('console')->middleware(['auth', 'permission:admin|console|editor'])->group(function () {
    Route::name('spec.')->prefix('speciality')->group(function () {
        Route::get('new', 'EditorController@SpecialityNew')->name('new');
        Route::post('create', 'EditorController@SpecialityCreate')->name('create');
        Route::get('{id}', 'EditorController@SpecialityEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SpecialityUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SpecialityDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SpecialityPairs')->name('pairs');
    });

    Route::name('branch.')->prefix('branch')->group(function () {
        Route::get('new', 'EditorController@BranchNew')->name('new');
        Route::post('create', 'EditorController@BranchCreate')->name('create');
        Route::get('{id}', 'EditorController@BranchEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@BranchUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@BranchDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@BranchPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@BranchUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@BranchUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@BranchUserPairs')->name('userpairs');
    });

    Route::name('subgroup.')->prefix('subgroup')->group(function () {
        Route::get('new', 'EditorController@SubgroupNew')->name('new');
        Route::post('create', 'EditorController@SubgroupCreate')->name('create');
        Route::get('{id}', 'EditorController@SubgroupEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SubgroupUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SubgroupDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SubgroupPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@SubgroupUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@SubgroupUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@SubgroupUserPairs')->name('userpairs');
        Route::post('testupdate/{id}', 'EditorController@SubgroupTestUpdate')->name('testupdate');
        Route::post('testsearch/', 'EditorController@SubgroupTestSearch')->name('testsearch');
        Route::post('testpairs/{id}', 'EditorController@SubgroupTestPairs')->name('testpairs');
    });

    Route::name('disc.')->prefix('discipline')->group(function () {
        Route::get('new', 'EditorController@DisciplineNew')->name('new');
        Route::post('create', 'EditorController@DisciplineCreate')->name('create');
        Route::get('{id}', 'EditorController@DisciplineEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@DisciplineUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@DisciplineDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@DisciplinePairs')->name('pairs');
        Route::post('branchupdate/{id}', 'EditorController@DisciplineBranchUpdate')->name('branchupdate');
        Route::post('branchsearch/', 'EditorController@DisciplineBranchSearch')->name('branchsearch');
        Route::post('branchpairs/{id}', 'EditorController@DisciplineBranchPairs')->name('branchpairs');
        Route::post('competences/{id}', 'EditorController@DisciplineCompetenceUpdate')->name('compupdate');
    });

    Route::name('competence.')->prefix('competence')->group(function () {
        Route::post('create', 'EditorController@CompetenceCreate')->name('create');
        Route::post('{id?}', 'EditorController@CompetenceEdit')->name('edit');
        Route::post('update/{id?}', 'EditorController@CompetenceUpdate')->name('update');
        Route::post('delete/{id?}', 'EditorController@CompetenceDelete')->name('delete');
    });

    Route::name('test.')->prefix('test')->group(function () {
        Route::get('new', 'EditorController@TestNew')->name('new');

app/Models/mddb/Discipline.php
<?php

namespace App\Models\mddb;

use Illuminate\Database\Eloquent\Model;

class Discipline extends Model
{
    protected $table = 'discipline'; 
    public $timestamps = false;

    protected $fillable = [
        'name',
        'portrait',
        'owner',
        'shortname',
        'status_id',
    ];

    protected $hidden = [

    ];

    /**
     * Связь Многие к Одному с User
     */
    public function userowner()
    {
        return $this->belongsTo(\App\Models\User::class, 'owner');
    }

    /**
     * Связь Многие к Одному с Disciplinestatus
     */
    public function disciplinestatus()
    {
        return $this->belongsTo(Disciplinestatus::class, 'status_id');
    }

    /**
     * Связь Многие к Многие с Branch
     */
    public function branches()
    {
        return $this->belongsToMany(Branch::class, 'branchlinkdisc', 'discipline_id', 'branch_id');
    }

    /**
     * Связь Многие к Многие с Test
     */
    public function tests()
    {
        return $this->hasMany(Test::class, 'discipline_id');
    }

    /**
     * Связь Многие к Многие с Competence
     */
    public function competences()
    {
        return $this->belongsToMany(Competence::class, 'disclinkcomp', 'discipline_id', 'competence_id');
    }

    /**
     * Связь один ко многим с EdElement
     */
    public function edelements()
    {
        return $this->hasMany(EdElement::class, 'discipline_id');
    }
}

app/Http/Controllers/Database/mddb/DisciplineController.php
<?php

namespace App\Http\Controllers\Database\mddb;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\mddb\Discipline;

class DisciplineController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Дисциплина
    |--------------------------------------------------------------------------
    */

    public function __construct()
    {
        // $this->middleware('')->only([ '' ]);
    }

    /**
     * Получение дисциплины
     *
     * GET /api/discipline/{id}
     *
     * @param int
     */
    public function model($id)
    {
        $disc = Discipline::find($id);

        if (!$disc) {
            return $this->toJson(['message' => 'Дисциплина не найдена'], 422);
        }

        $disc->load([
            'userowner',
            'disciplinestatus',
        ])
            ->setHidden([
                'owner',
                'status',
            ]);

        return $this->toJson($disc);
    }

    /**
     * Получение списка дисциплин
     *
     * POST /api/disciplines
     *
     * @param \Illuminate\Http\Request
     */
    public function models(Request $request)
    {
        $discs = Discipline::query();

        if ($request->has('name')) {
            $discs->where('name', 'like', str_replace("*", "%", $request->name));
        }

        if ($request->has('shortname')) {
            $discs->where('shortname', 'like', str_replace("*", "%", $request->shortname));
        }

        $discs = $discs->with([
            'userowner',
            'disciplinestatus'
        ])
            ->get();

        $discs = $this->modelsPaginator($discs, $request->perPage, $request->pageCount);

        return $this->toJson($discs);
    }

    /**
     * Список компетенций для дисциплины
     *
     * GET /api/discipline/{id}competences
     *
     * @param int
     */
    public function competences($id)
    {
        $disc = Discipline::find($id);

        if (!$disc) {
            return $this->toJson(['message' => 'Дисциплина не найдена'], 422);
        }

        $competences = $disc->competences;

        if ($competences->count() === 0) {
            return $this->toJson(['message' => 'Компетенций для дисциплины не найдено'], 422);
        }

        return $this->toJson($competences);
    }

    /**
     * Список тестов для дисциплины
     *
     * GET /api/discpiline/{id}/tests
     *
     * @param int
     * @param \Illuminate\Http\Request
     */
    public function tests($id, Request $request)
    {
        $disc = Discipline::find($id);

        if (!$disc) {
            return $this->toJson(['message' => 'Дисциплина не найдена'], 422);
        }

        $tests = $disc->tests->where('option', $request->option)->first();

        if ($tests->count() === 0) {
            return $this->toJson(['message' => 'Тестов для дисциплины не найдено'], 422);
        }

        return $this->toJson($tests);
    }
}

resources/views/editor/discipline/create.blade.php
@extends('layouts.main', ['title' => config('app.name').' - Создание дисциплины'])

@section('style')

<link rel="stylesheet" type="text/css" href="{{ asset('css/editor/simditor.css') }}" />

@endsection

@section('content')

<div class="ui stackable centered grid">
    
    <div class="twelve wide column">
        
        <div class="ui tiny breadcrumb">
            <a class="section bread" href="{{ route('console.main') }}">Консоль</a>
            <i class="right angle icon divider"></i>
            <a class="section bread" href="{{ route('console.disc.main') }}">Дисциплины</a>
            <i class="right angle icon divider"></i>
            <div class="section active">Создать</div>
        </div>
        
        <div class="ui divider"></div>
        
        @include('editor.discipline.parts.edit')
        
    </div>
</div>

@endsection

@section('script')

@include('editor.discipline.parts.script')

<script type="text/javascript" src="{{ asset('js/editor/module.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/editor/hotkeys.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/editor/simditor.min.js') }}"></script>
<script type="text/javascript">
    $("input[type=text], #status").click(function(){
        $(this).closest(".field")
               .removeClass("error")
               .children(".ui.basic.label")
               .slideUp(50, function(){ $(this).remove(); });
    });
    
    let editor = new Simditor({
        toolbar: [
            "bold", "italic", "underline", "strikethrough", "color", "|",
            "ol", "ul", "|",
            "indent", "outdent", "|",
             "link", "hr"
        ],
        textarea: $("#portrait"),
        placeholder: "Описание дисциплины"
    });
    
    $("#btn-save").click(function(){ $(this).addClass("loading") });
    $("#status").dropdown("set selected", "{{ old('status') }}");
</script>

@endsection

resources/views/editor/discipline/edit.blade.php
@extends('layouts.main', ['title' => config('app.name').' - Дисциплина - '.$disc->name])

@section('style')

<link rel="stylesheet" type="text/css" href="{{ asset('css/editor/simditor.css') }}" />

@endsection

@section('content')

<div class="ui centered grid">
    
    <div class="sixteen wide mobile tablet twelve wide computer centered column">

        <div class="ui tiny breadcrumb">
            <a class="section bread" href="{{ route('console.main') }}">Консоль</a>
            <i class="right angle icon divider"></i>
            <a class="section bread" href="{{ route('console.disc.main') }}">Дисциплины</a>
            <i class="right angle icon divider"></i>
            <div class="section active">#{{ $disc->id }}</div>
        </div>
        
        <div class="ui divider"></div>
        
        {{-- ОСНОВНЫЕ ПАРАМЕТРЫ --}}
        <div class="ui fluid accordion">
            <div class="title active">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Основные параметры</b>
            </div>


            <div class="content active">

                <div class="main-holder" route-pairs="{{ route('editor.disc.pairs', [$disc->id]) }}" route-update="{{ route('editor.disc.update', ['id' => $disc->id]) }}">

                    @include('editor.discipline.parts.info')

                </div>

            </div>

        </div>

        <div class="ui divider"></div>

        {{-- ФАКУЛЬТАТИВНЫЕ ГРУППЫ --}}
        <div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Факультативные группы</b>
            </div>

            <div class="content">

                <br/>
                <div class="link-holder" route-pairs="{{ route('editor.disc.branchpairs', [$disc->id]) }}" route-search="{{ route('editor.disc.branchsearch') }}" route-update="{{ route('editor.disc.branchupdate', [$disc->id]) }}" model="branches">

                    @include('editor.discipline.parts.tablebranch')

                </div>

            </div>
        </div>

        <div class="ui divider"></div>

        {{-- АНКЕТЫ И ТЕСТЫ --}}
        <div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Анкеты и тесты</b>
            </div>

            <div class="content">

                <br/>
                <div>

                    @include('editor.discipline.parts.tabletest')

                </div>

            </div>
        </div>

        <div class="ui divider"></div>

        {{-- СЛОВАРЬ КОМПЕТЕНЦИЙ --}}
        <div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Компетенции</b>
            </div>

            <div class="content">

                <br/>
                <div class="link-holder" route-update="{{ route('editor.disc.compupdate', [$disc->id]) }}">

                    @include('editor.discipline.parts.tablecompetence')

                </div>

            </div>
        </div>

        {{-- СЛОВАРЬ ДИДАКТИЧЕСКИХ ЕДИНИЦ --}}
        {{--<div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Дидактические единицы</b>
            </div>

            <div class="content active1">

                <br/>
                <div id="link-holder">

                    @@include('editor.discipline.parts.tabledidactic')

                </div>

            </div>
        </div>--}}

        {{-- СЛОВАРЬ ЗАДАЧ --}}
        {{--<div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Задачи</b>
            </div>

            <div class="content">

                <br/>
                <div id="link-holder">

                    @include('editor.discipline.parts.tabletask')

                </div>

            </div>
        </div>--}}

        {{-- СЛОВАРЬ МЕТОДОВ --}}
        {{--<div class="ui fluid accordion">
            <div class="title">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Методы</b>
            </div>

            <div class="content">

                <br/>
                <div id="link-holder">

                    @include('editor.discipline.parts.tablemethod')

                </div>

            </div>
        </div>--}}

    </div>
</div>

@endsection

@section('script')

@include('editor.parts.attach')
@include('editor.discipline.parts.script')

<script type="text/javascript" src="{{ asset('js/editor/module.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/editor/hotkeys.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/editor/simditor.min.js') }}"></script>
<script type="text/javascript">
    {{-- КНОПКА УДАЛИТЬ [button_delete] --}}
    const bd = function(){
        let val = confirm("Вы уверены, что хотите удалить дисциплину?");

        if (val) $(".main-holder form").attr("action", "{{ route('editor.disc.delete', [$disc->id]) }}").off("submit").submit();
    };
    {{-- ИНИЦИАЛИЗАЦИЯ РЕДАКТОРА ОПИСАНИЯ [initialize_editor] --}}
    const ie = function(){
        let editor = new Simditor({
            toolbar: [
                "bold", "italic", "underline", "strikethrough", "color", "|",
                "ol", "ul", "|",
                "indent", "outdent", "|",
                 "link", "hr"
            ],
            textarea: $("#portrait"),
            placeholder: "Вступительное описание теста"
        });
    };
    {{-- УДАЧНОЕ ОБНОВЛЕНИЕ МОДЕЛИ [on_success] --}}
	const osc = function(holder, data, edit){
		holder.empty().append(data.view);
		holder.find("#btn-pairs").click(function(){ gmf(this) });

        console.log(data);

		if (edit){
			ie(); // [initialize_editor]
			holder.find("form").submit(bms);
			holder.find("#btn-delete").click(bd);
			holder.find("#status").dropdown("set selected", `${data.disc.status}`);
		}
	};
    
    console.log($(".link-holder form").find("#btn-pairs"))
    
    $(".main-holder #btn-pairs").click(function(){ gmf(this) });
    $(".link-holder form").find("#btn-pairs").click(gaf);
    $(".link-holder form").find("#btn-save").click(bas);
</script>


@endsection