routes/web.php
| Отладка и пробы
|--------------------------------------------------------------------------
*/

Route::middleware('debug')->group(function () {
    Route::get('/purpose-grid-only', 'Other\DevelopController@grid');
    Route::any('/purpose-test-only', 'Other\DevelopController@test');
});

Route::get('/cache/flm-builder', 'Other\CacheController@flmBuilderStat');

/*
|--------------------------------------------------------------------------
| Консольные пути по выдачи Blade компонентов [ ПЕРЕПИСАТЬ ]
|--------------------------------------------------------------------------
*/

/**
 * Консоль
 */
Route::name('console.')->prefix('console')->middleware(['auth', 'permission:admin|console'])->group(function () {
    Route::get('', 'ConsoleController@main')->name('main');

    Route::name('spec.')->group(function () {
        Route::get('specialities', 'ConsoleController@Speciality')->name('main');
    });

    Route::name('branch.')->group(function () {
        Route::get('branches', 'ConsoleController@Branch')->name('main');
        Route::post('branches', 'ConsoleController@BranchNext')->name('next');
        Route::post('branches/search', 'ConsoleController@BranchSearch')->name('search');
    });

    Route::name('subgroup.')->group(function () {
        Route::get('subgroups', 'ConsoleController@Subgroup')->name('main');
        Route::post('subgroups', 'ConsoleController@SubgroupNext')->name('next');
        Route::post('subgroups/search', 'ConsoleController@SubgroupSearch')->name('search');
    });

    Route::name('disc.')->group(function () {
        Route::get('disciplines', 'ConsoleController@Discipline')->name('main');
        Route::post('disciplines', 'ConsoleController@DisciplineNext')->name('next');
        Route::post('disciplines/search', 'ConsoleController@DisciplineSearch')->name('search');
    });

    Route::name('competence.')->group(function () {
        Route::get('competences', 'ConsoleController@Competence')->name('main');
        Route::post('competence', 'ConsoleController@CompetenceNext')->name('next');
    });

    Route::name('test.')->group(function () {
        Route::get('tests', 'ConsoleController@Test')->name('main');
        Route::post('tests', 'ConsoleController@TestNext')->name('next');
        Route::post('tests/search', 'ConsoleController@TestSearch')->name('search');
    });

    Route::name('quest.')->group(function () {
        Route::get('quests', 'ConsoleController@Quest')->name('main');
        Route::post('quests', 'ConsoleController@QuestNext')->name('next');
        Route::post('quests/search', 'ConsoleController@QuestSearch')->name('search');
    });

    Route::name('user.')->group(function () {
        Route::get('users', 'ConsoleController@User')->name('main');
        Route::post('users', 'ConsoleController@UserNext')->name('next');
        Route::post('users/search', 'ConsoleController@UserSearch')->name('search');
    });

    Route::name('passed.')->group(function () {
        Route::get('passed', 'ConsoleController@Passed')->name('main');
        Route::post('passed', 'ConsoleController@PassedNext')->name('next');
        Route::post('passed/search', 'ConsoleController@PassedSearch')->name('search');
        Route::get('passed/download/{id}', 'ConsoleController@PassedDownload')->name('download');
    });

    Route::name('conference.')->group(function () {
        Route::get('conference', 'ConsoleController@Conference')->name('main');
    });

    Route::name('develop.')->middleware(['permission:develop'])->group(function () {
        Route::get('develop', 'ConsoleController@Develop')->name('main');
    });
});

/**
 * Редактор
 */
Route::prefix('editor')->middleware(['auth', 'permission:admin|console'])->group(function () {
    /** Редактирование статьи */
    Route::get('/article/{id}', 'EditorController@Article');

    /** Редактирование участника */
    Route::get('/member/{id}', 'EditorController@Member');
});

Route::name('editor.')->prefix('console')->middleware(['auth', 'permission:admin|console|editor'])->group(function () {
    Route::name('spec.')->prefix('speciality')->group(function () {
        Route::get('new', 'EditorController@SpecialityNew')->name('new');
        Route::post('create', 'EditorController@SpecialityCreate')->name('create');
        Route::get('{id}', 'EditorController@SpecialityEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SpecialityUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SpecialityDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SpecialityPairs')->name('pairs');
    });

    Route::name('branch.')->prefix('branch')->group(function () {
        Route::get('new', 'EditorController@BranchNew')->name('new');
        Route::post('create', 'EditorController@BranchCreate')->name('create');
        Route::get('{id}', 'EditorController@BranchEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@BranchUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@BranchDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@BranchPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@BranchUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@BranchUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@BranchUserPairs')->name('userpairs');
    });

    Route::name('subgroup.')->prefix('subgroup')->group(function () {
        Route::get('new', 'EditorController@SubgroupNew')->name('new');
        Route::post('create', 'EditorController@SubgroupCreate')->name('create');
        Route::get('{id}', 'EditorController@SubgroupEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@SubgroupUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@SubgroupDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@SubgroupPairs')->name('pairs');
        Route::post('userupdate/{id}', 'EditorController@SubgroupUserUpdate')->name('userupdate');
        Route::post('usersearch/', 'EditorController@SubgroupUserSearch')->name('usersearch');
        Route::post('userpairs/{id}', 'EditorController@SubgroupUserPairs')->name('userpairs');
        Route::post('testupdate/{id}', 'EditorController@SubgroupTestUpdate')->name('testupdate');
        Route::post('testsearch/', 'EditorController@SubgroupTestSearch')->name('testsearch');
        Route::post('testpairs/{id}', 'EditorController@SubgroupTestPairs')->name('testpairs');
    });

    Route::name('disc.')->prefix('discipline')->group(function () {
        Route::get('new', 'EditorController@DisciplineNew')->name('new');
        Route::post('create', 'EditorController@DisciplineCreate')->name('create');
        Route::get('{id}', 'EditorController@DisciplineEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@DisciplineUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@DisciplineDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@DisciplinePairs')->name('pairs');
        Route::post('branchupdate/{id}', 'EditorController@DisciplineBranchUpdate')->name('branchupdate');
        Route::post('branchsearch/', 'EditorController@DisciplineBranchSearch')->name('branchsearch');
        Route::post('branchpairs/{id}', 'EditorController@DisciplineBranchPairs')->name('branchpairs');
        Route::post('competences/{id}', 'EditorController@DisciplineCompetenceUpdate')->name('compupdate');
    });

    Route::name('competence.')->prefix('competence')->group(function () {
        Route::post('create', 'EditorController@CompetenceCreate')->name('create');
        Route::post('{id?}', 'EditorController@CompetenceEdit')->name('edit');
        Route::post('update/{id?}', 'EditorController@CompetenceUpdate')->name('update');
        Route::post('delete/{id?}', 'EditorController@CompetenceDelete')->name('delete');
    });

    Route::name('test.')->prefix('test')->group(function () {
        Route::get('new', 'EditorController@TestNew')->name('new');
        Route::post('create', 'EditorController@TestCreate')->name('create');
        Route::get('{id}', 'EditorController@TestEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@TestUpdate')->name('update');
        Route::post('access/{id}', 'EditorController@TestAccess')->name('access');
        Route::post('delete/{id}', 'EditorController@TestDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@TestPairs')->name('pairs');
        Route::post('questsupdate/{id}', 'EditorController@TestQuestUpdate')->name('questupdate');
        Route::post('questssearch/', 'EditorController@TestQuestSearch')->name('questsearch');
        Route::post('questspairs/{id}', 'EditorController@TestQuestPairs')->name('questpairs');
    });

    Route::name('quest.')->prefix('quest')->group(function () {
        Route::get('new', 'EditorController@QuestNew')->name('new');
        Route::post('create', 'EditorController@QuestCreate')->name('create');
        Route::get('{id}', 'EditorController@QuestEdit')->name('edit');
        Route::post('update/{id}', 'EditorController@QuestUpdate')->name('update');
        Route::post('delete/{id}', 'EditorController@QuestDelete')->name('delete');
        Route::post('pairs/{id}', 'EditorController@QuestPairs')->name('pairs');
        Route::post('competences/{id}', 'EditorController@QuestCompetenceUpdate')->name('compupdate');
        Route::post('admatrix/{id}', 'EditorController@QuestMatrixUpdate')->name('matrixupdate');
    });

    Route::name('user.')->prefix('user')->group(function () {
        Route::get('{id}', 'EditorController@UserEdit')->name('edit');
        Route::post('delete/{id}', 'EditorController@UserDelete')->name('delete');

app/Models/conf/Article.php
<?php

namespace App\Models\conf;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    const CREATED_AT = 'created_at';
    const UPDATED_AT = null;

    protected $connection = 'conf';
    protected $table = 'article';
    public $timestamps = true;

    protected $fillable = [
        'name',
        'section_id',
        'status_id',
        'created_at',
    ];

    protected $hidden = [

    ];

    protected $casts = [
        'created_at' => 'datetime',
    ];

    /**
     * Связь Многие к Одному с Section
     */
    public function section()
    {
        return $this->belongsTo(Section::class, 'section_id');
    }

    /**
     * Связь Многие к Одному с Status
     */
    public function status()
    {
        return $this->belongsTo(Status::class, 'status_id');
    }

    /**
     * Связь Один к Многие с Document
     */
    public function documents()
    {
        return $this->hasMany(Document::class, 'article_id');
    }

    /**
     * Связь Многие к Многие с Member
     */
    public function members()
    {
        return $this->belongsToMany(Member::class, 'memberlinkarticle', 'article_id', 'member_id');
    }
}

app/Http/Controllers/Database/conf/ArticleController.php
<?php

namespace App\Http\Controllers\Database\conf;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

use App\Models\conf\Member;
use App\Models\conf\Status;
use App\Models\conf\Article;

class ArticleController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Статья на конференцию
    |--------------------------------------------------------------------------
    */

    public function __construct()
    {
        // $this->middleware('')->only([ '' ]);
    }

    /**
     * Получение статьи
     *
     * GET /api/conf/article/{id}
     */
    public function article($id)
    {
        $article = Article::find($id);

        if (!$article)
            return $this->toJson(['message' => 'Научная статья не найдена'], 422);

        $article->load([
            'status',
            'section',
            'members',
            'documents',
        ]);

        return $this->toJson($article);
    }

    /**
     * Обновление статуса статьи
     *
     * PUT /api/conf/article/{id}/status
     */
    public function status(Request $request, $id)
    {
        if (!$request->filled('statusId'))
            return $this->toJson(['message' => 'Запрос не верно построен'], 422);

        $article = Article::find($id);

        if (!$article)
            return $this->toJson(['message' => 'Научная статья не найдена'], 422);

        $article->status_id = $request->statusId;
        $article->save();

        return $this->toJson(['result' => true]);
    }

    /**
     * Изменение списка участников для статьи
     *
     * PUT /api/conf/article/{id}/members
     */
    public function putMembers(Request $request, $id)
    {
        abort(501);

        $article = Article::find($id);

        if (!$article)
            return $this->toJson(['message' => 'Научная статья не найдена'], 422);
    }

    /**
     * Удаление статьи
     *
     * DELETE /api/conf/article/{id}
     */
    public function delete($id)
    {
        $article = Article::find($id);

        if (!$article)
            return $this->toJson(['message' => 'Научная статья не найдена'], 422);

        $path = 'conference/' . $article->id . '_' . $article->created_at->timestamp;

        Storage::deleteDirectory($path);

        $article->delete();

        return $this->toJson(['result' => true]);
    }

    /**
     * Получение списка статей
     *
     * POST /api/conf/articles
     */
    public function articles(Request $request)
    {
        $articles = Article::query();

        if ($request->filled('name'))
            $articles->whereName($request->name);
        if ($request->filled('status') && (int) $request->status)
            $articles->whereStatusId($request->status);
        if ($request->filled('year') && (int) $request->year)
            $articles->whereYear('created_at', $request->year);

        if ($request->filled('sort')) {
            if ($request->sort === 'o')
                $articles->orderBy('name');  // По имени (А-Я)
            else if ($request->sort === 'n')
                $articles->orderByDesc('name');  // По имени (Я-А)

            if ($request->sort === 'co')
                $articles->orderBy('created_at');  // По дате (старые)
            else if ($request->sort === 'cn')
                $articles->orderByDesc('created_at');  // По дате (новые)
        }

        $articles = $articles->with(['section'])->get();
        $total = $articles->count();

        $articles = $this->modelsPaginator($articles, $request->perPage, $request->pageCount);

        if ($request->has('html')) {
            $articles = $articles->map(function ($elem) {
                return \View::make('console.conference.parts.article', [
                    'article' => $elem,
                ])->render();
            })->values();
        }

        return $this->toJson([
            'data' => $articles,
            'total' => $total,
        ]);
    }
}

resources/views/editor/conference/article/edit.blade.php
@extends('layouts.main', ['title' => config('app.name').' - Заявленная статья  - '.$article->name])

@section('content')

<div class="ui centered grid">

    <div class="sixteen wide mobile tablet twelve wide computer centered column">

        <div class="ui tiny breadcrumb">
            <a class="section bread" href="{{ route('console.main') }}">Консоль</a>
            <i class="right angle icon divider"></i>
            <a class="section bread" href="{{ route('console.conference.main') }}">Конференция</a>
        </div>

        <div class="ui divider"></div>

        {{-- ОСНОВНЫЕ ПАРАМЕТРЫ --}}
        <div class="ui fluid accordion">
            <div class="title active">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Основные параметры</b>
            </div>


            <div class="content active">

                <div class="main-holder">

                    @include('editor.conference.article.parts.info')

                </div>

            </div>
        </div>

        <div class="ui divider"></div>

        {{-- СПИСОК УЧАСТНИКОВ --}}
        <div class="ui fluid accordion">
            <div class="title active">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Авторы</b>
            </div>

            <div class="content active">
                <br/>
                <div class="link-holder">

                    @include('editor.conference.article.parts.tablemember')


                </div>
            </div>
        </div>

        <div class="ui divider"></div>

        {{-- ПРИЛОЖЕННЫЕ ФАЙЛЫ --}}
        <div class="ui fluid accordion">
            <div class="title active">
                <i class="dropdown icon"></i>
                <b style="font-size:1.25rem;">Приложенные документы</b>
            </div>

            <div class="content active">
                <br/>
                <div class="link-holder">

                    @include('editor.conference.article.parts.tabledocument')


                </div>
            </div>
        </div>

    </div>
</div>

@endsection

@section('script')

<script type="text/javascript">
    $('#delete-item').click(function() {

        const isDelete = confirm("Вы уверены, что хотите удалить статью безвозвратно?");

        if (!isDelete) {
            return
        }

        $.ajax({
            type: 'DELETE',
            url: `/api/conf/article/{{ $article->id }}`,
            headers: { "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr('content') },
        })
            .done(data => {
                window.location.href = '/console/conference'
            })
            .fail((jqXHR, textStatus, errorThrown) => {
                console.log('$ jqXHR', jqXHR)
                console.log('$ textStatus', textStatus)
                console.log('$ errorThrown', errorThrown)
            })
            .always(() => {

            })
    })

    $('#status').dropdown('set selected', {{ $article->status->id }})
        .dropdown({
            onChange: function (index) {
                $(this).addClass('loading')

                $.ajax({
                        type: 'PUT',
                        url: `/api/conf/article/{{ $article->id }}/status`,
                        data: { statusId: index },
                        headers: { "X-CSRF-TOKEN": $("meta[name='csrf-token']").attr('content') },
                    })
                    .done(data => {
                        
                    })
                    .fail((jqXHR, textStatus, errorThrown) => {
                        console.log('$ jqXHR', jqXHR)
                        console.log('$ textStatus', textStatus)
                        console.log('$ errorThrown', errorThrown)
                    })
                    .always(() => {
                        $(this).removeClass('loading')
                    })
            }
    })

</script>


@endsection